name: Deploy manual de uma tag para Azure

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag do repositório para fazer o deploy'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout tag selecionada
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Set up Python version
      uses: actions/setup-python@v4
      with: 
        python-version: '3.11' # ou 3.13, se suportado

    - name: Set up cache dependency
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Criar e usar venv + instalar dependências
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with: 
        app-name: meu-app-pipeline
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
